# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 995dd29a833e795a76494c2c9d0b6bf83cb12cb7a9d186563e9746b2b58af1ac52cb915fcac0f616cc6e859853d2e427097021cbae401fbd5b47cc3992fcfcfb

test:
  secret_key_base: 1206448e31cd79f833b7d9b1c8c31aa8ad3c3efc5388b1c4a76710dcb4d4326df32adc8a4103812709781befc104e092db8dd3d9849ae597319c5d2297c3f864

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
